version: '3'
services:
    mp-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
        container_name: mp-elasticsearch
        environment:
            - discovery.type=single-node
            # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            # ulimits:
            #   memlock:
            #       soft: -1
            #       hard: -1
        ports:
            - "127.0.0.1:9200:9200"
        networks:
            marketplace:

    mp-mongo:
        image: mongo:3.2
        container_name: mp-mongo
        networks:
            marketplace:
                aliases:
                    - mp-mongo.docker
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root_pw
            MONGO_INITDB_DATABASE: root_db
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            # Uncomment for data persistance
            #- ./mongo-data:/data/db

    mp-mysql:
        image: mysql:5.7
        container_name: mp-mysql
        volumes:
            - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
            # Uncomment for data persistance
            #- ./mysql-data:/var/lib/mysql
        networks:
            marketplace:
                aliases:
                    - mp-mysql.docker
        environment:
            - MYSQL_ROOT_PASSWORD=root_pw
            #- MYSQL_DATABASE=RSS

    mp-apis:
        image: fiware/biz-ecosystem-apis
        container_name: mp-apis
        ports:
            - 4848:4848
            - 8080:8080
        links:
            - mp-mysql
        depends_on:
            - mp-mysql
        networks:
            marketplace:
                aliases:
                    - apis.docker
        volumes:
        #    - ./apis-conf:/etc/default/tmf/  # Used if not configured by environment
            - ./apis-wars:/apis/wars-ext
        environment:
            - BAE_SERVICE_HOST=http://proxy.docker:8004/
            - MYSQL_ROOT_PASSWORD=root_pw
            - MYSQL_HOST=mp-mysql.docker

    mp-rss:
        image: fiware/biz-ecosystem-rss
        container_name: mp-rss
        #restart: always
        ports:
            - 9999:8080
            - 4444:4848
            - 1111:8181
        links:
            - mp-mysql
        depends_on:
            - mp-mysql
            - mp-apis
        networks:
            marketplace:
                aliases:
                    - rss.docker
        # volumes:
        #    - ./rss-conf:/etc/default/rss  # Used if not configured by environment
        environment:
            - MYSQL_HOST=mp-mysql.docker
            - MYSQL_PORT=3306
            - BAE_RSS_DATABASE_URL=jdbc:mysql://mp-mysql.docker:3306/RSS
            - BAE_RSS_DATABASE_USERNAME=root
            - BAE_RSS_DATABASE_PASSWORD=root_pw
            - BAE_RSS_DATABASE_DRIVERCLASSNAME=com.mysql.jdbc.Driver
            - BAE_RSS_OAUTH_CONFIG_GRANTEDROLE=admin
            - BAE_RSS_OAUTH_CONFIG_SELLERROLE=seller
            - BAE_RSS_OAUTH_CONFIG_AGGREGATORROLE=Aggregator

    mp-charging:
        image: fiware/biz-ecosystem-charging-backend
        container_name: mp-charging
        networks:
            marketplace:
                aliases:
                    - charging.docker
        ports:
            - 8006:8006
        depends_on:
            - mp-mongo
            - mp-apis
            - mp-rss
        volumes:
            # - ./charging-settings:/business-ecosystem-charging-backend/src/user_settings  # Used if the settings files are provided through the volume
            #- ./entrypoint.sh:/entrypoint.sh
            - ./charging-bills:/business-ecosystem-charging-backend/src/media/bills
            - ./charging-assets:/business-ecosystem-charging-backend/src/media/assets
            - ./charging-plugins:/business-ecosystem-charging-backend/src/plugins
            - ./charging-inst-plugins:/business-ecosystem-charging-backend/src/wstore/asset_manager/resource_plugins/plugins
        environment:
          - BAE_CB_PAYMENT_METHOD=None  # paypal or None (testing mode payment disconected)
          # - BAE_CB_PAYPAL_CLIENT_ID=client_id
          # - BAE_CB_PAYPAL_CLIENT_SECRET=client_secret

          # ----- Database configuration ------
          - BAE_CB_MONGO_SERVER=mp-mongo.docker
          - BAE_CB_MONGO_PORT=27017
          - BAE_CB_MONGO_DB=charging_db
          - BAE_CB_MONGO_USER=charging
          - BAE_CB_MONGO_PASS=charging_pw

          # ----- Roles Configuration -----
          - BAE_LP_OAUTH2_ADMIN_ROLE=admin
          - BAE_LP_OAUTH2_SELLER_ROLE=seller
          - BAE_LP_OAUTH2_CUSTOMER_ROLE=customer

          # ----- Email configuration ------
          - BAE_CB_EMAIL=charging@email.com
          # - BAE_CB_EMAIL_USER=user
          # - BAE_CB_EMAIL_PASS=pass
          # - BAE_CB_EMAIL_SMTP_SERVER=smtp.server.com
          # - BAE_CB_EMAIL_SMTP_PORT=587

          - BAE_CB_VERIFY_REQUESTS=True  # Whether or not the BAE validates SSL certificates on requests to external components 

          # ----- Site configuration -----
          - BAE_SERVICE_HOST=http://proxy.docker:8004/  # External URL used to access the BAE
          - BAE_CB_LOCAL_SITE=http://charging.docker:8006/  # Local URL of the charging backend

          # ----- APIs Connection config -----
          - BAE_CB_CATALOG=http://apis.docker:8080/DSProductCatalog
          - BAE_CB_INVENTORY=http://apis.docker:8080/DSProductInventory
          - BAE_CB_ORDERING=http://apis.docker:8080/DSProductOrdering
          - BAE_CB_BILLING=http://apis.docker:8080/DSBillingManagement
          - BAE_CB_RSS=http://rss.docker:8080/DSRevenueSharing
          - BAE_CB_USAGE=http://apis.docker:8080/DSUsageManagement
          - BAE_CB_AUTHORIZE_SERVICE=http://proxy.docker:8004/authorizeService/apiKeys


    mp-proxy:
        image: fiware/biz-ecosystem-logic-proxy
        container_name: mp-proxy
        links:
            - mp-mongo
            - mp-elasticsearch
        depends_on:
            - mp-mongo
            - mp-elasticsearch
            - mp-apis
            - mp-rss
            - mp-charging
        networks:
            marketplace:
                aliases:
                    - proxy.docker
        ports:
            - 8004:8004
        volumes:
            # - ./proxy-conf:/business-ecosystem-logic-proxy/etc  # To be used when congiguring the system with a config file provided in the volume
            - ./proxy-indexes:/business-ecosystem-logic-proxy/indexes
            - ./proxy-themes:/business-ecosystem-logic-proxy/themes
            - ./proxy-static:/business-ecosystem-logic-proxy/static
            - ./proxy-locales:/business-ecosystem-logic-proxy/locales
        environment:
            - NODE_ENV=development  # Deployment in development or in production
            - COLLECT=True  # Execute the collect static command on startup

            - BAE_LP_PORT=8004  # Port where the node service is going to run in the container
            - BAE_LP_HOST=proxy.docker  # Host where the node service if going to run in the container
            # - BAE_SERVICE_HOST=https://store.lab.fiware.org/  # If provided, this URL specifies the actual URL that is used to access the BAE, when the component is proxied (e.g Apache)
            # - BAE_LP_HTTPS_ENABLED=true  # If provided specifies whether the service is running in HTTPS, default: false
            # - BAE_LP_HTTPS_CERT=cert/cert.crt  # Certificate for the SSL configuration (when HTTPS enabled is true)
            # - BAE_LP_HTTPS_CA=cert/ca.crt  # CA certificate for the SSL configuration (when HTTPS enabled is true)
            # - BAE_LP_HTTPS_KEY=cert/key.key  # Key sfile for the SSL configuration (when HTTPS enabled is true)
            # - BAE_LP_HTTPS_PORT=443  # Port where the service runs when SSL is enabled (when HTTPS enabled is true)

            # ------ OAUTH2 Config ------
            - BAE_LP_OAUTH2_SERVER=http://idm.docker:3000  # URL of the FIWARE IDM used for user authentication
            - BAE_LP_OAUTH2_CLIENT_ID=85e62a00-318a-4763-8cff-1ae305e84b8b  # OAuth2 Client ID of the BAE applicaiton
            - BAE_LP_OAUTH2_CLIENT_SECRET=0654b9d6-70c2-4216-9e62-17eaeb8a5436  # OAuth Client Secret of the BAE application
            - BAE_LP_OAUTH2_CALLBACK=http://proxy.docker:8004/auth/fiware/callback  # Callback URL for receiving the access tokens
            - BAE_LP_OAUTH2_ADMIN_ROLE=admin  # Role defined in the IDM client app for admins of the BAE 
            - BAE_LP_OAUTH2_SELLER_ROLE=seller  # Role defined in the IDM client app for sellers of the BAE 
            - BAE_LP_OAUTH2_CUSTOMER_ROLE=customer  # Role defined in the IDM client app for customers of the BAE 
            - BAE_LP_OAUTH2_ORG_ADMIN_ROLE=orgAdmin  # Role defined in the IDM client app for organization admins of the BAE 
            - BAE_LP_OAUTH2_IS_LEGACY=false  # Whether the used FIWARE IDM is version 6 or lower

            # - BAE_LP_THEME=theme  # If provided custom theme to be used by the web site, it must be included in themes volume

            # ----- Mongo Config ------
            - BAE_LP_MONGO_USER=belp
            - BAE_LP_MONGO_PASS=belp_pw
            - BAE_LP_MONGO_SERVER=mp-mongo.docker
            - BAE_LP_MONGO_PORT=27017
            - BAE_LP_MONGO_DB=belp_db

            - BAE_LP_REVENUE_MODEL=30  # Default market owner precentage for Revenue Sharing models

            # ----- APIs Configuration -----
            # If provided, it supports configuring the contection to the different APIs managed by the logic proxy, by default
            # apis.docker, charging.docker and rss.docker domains are configured
            # - BAE_LP_ENDPOINT_CATALOG_PATH=DSProductCatalog
            # - BAE_LP_ENDPOINT_CATALOG_PORT=8080
            # - BAE_LP_ENDPOINT_CATALOG_HOST=apis.docker
            # - BAE_LP_ENDPOINT_CATALOG_SECURED=false
            # ...




networks:
    marketplace:
        external: true
